# Generated by Django 3.0.3 on 2020-02-26 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20200226_1306'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='thumbail_img',
            new_name='thumbnail_img',
        ),
    ]
