# Generated by Django 3.0.3 on 2020-02-29 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20200228_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='purpose',
            field=models.CharField(choices=[('BG', 'Blog'), ('CS', 'Case Study')], default='BG', max_length=2),
            preserve_default=False,
        ),
    ]
