# Generated by Django 3.0.3 on 2020-03-02 15:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_auto_20200301_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='read_minutes',
            field=models.PositiveIntegerField(default=11),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='form',
            name='phone_number',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
