# Generated by Django 3.0.3 on 2020-03-02 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_auto_20200302_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='read_minutes',
            field=models.PositiveIntegerField(help_text='Time needed in minutes to read this Insight'),
        ),
    ]
