# Generated by Django 3.0.3 on 2020-03-04 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_auto_20200304_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='read_minutes',
            field=models.PositiveIntegerField(blank=True, help_text='Time needed in minutes to read this Insight'),
        ),
    ]
