# Generated by Django 3.0.3 on 2020-04-01 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_auto_20200304_1306'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=255)),
                ('linkedin_url', models.URLField(max_length=255)),
                ('image', models.ImageField(upload_to='aboutus')),
            ],
        ),
    ]
