# Generated by Django 3.0.3 on 2020-04-01 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_aboutus'),
    ]

    operations = [
        migrations.CreateModel(
            name='MicrosoftDynamics365',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField(max_length=180)),
                ('purpose', models.CharField(choices=[('SS', 'Solutions')], default='SS', max_length=2)),
            ],
            options={
                'verbose_name': 'Microsoft Dynamics 365',
                'verbose_name_plural': 'Microsoft Dynamics 365',
            },
        ),
        migrations.CreateModel(
            name='PowerPlatform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceNow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField(max_length=255)),
            ],
        ),
        migrations.AlterModelOptions(
            name='aboutus',
            options={'verbose_name': 'About Us', 'verbose_name_plural': 'About Us'},
        ),
    ]
