# Generated by Django 3.0.3 on 2020-04-03 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0017_auto_20200403_0932'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='powerplatform',
            options={'ordering': ('order',)},
        ),
        migrations.AlterField(
            model_name='powerplatform',
            name='order',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=2, null=True),
        ),
    ]
