# Generated by Django 3.0.3 on 2020-04-03 13:50

from django.db import migrations, models
import posts.validators


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0018_auto_20200403_0934'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='microsoftdynamics365',
            options={'ordering': ('order',), 'verbose_name': 'Microsoft Dynamics 365', 'verbose_name_plural': 'Microsoft Dynamics 365'},
        ),
        migrations.AddField(
            model_name='microsoftdynamics365',
            name='order',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=2, null=True, validators=[posts.validators.md_order_validator]),
        ),
        migrations.AlterField(
            model_name='powerplatform',
            name='order',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=2, null=True, validators=[posts.validators.powerplatform_order_validator]),
        ),
    ]
