# Generated by Django 3.0.3 on 2020-04-04 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0022_jobprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobprofile',
            name='experience_years',
            field=models.CharField(choices=[('0 - 1', '0 - 1'), ('1 - 2', '1 - 2'), ('2 - 3', '2 - 3'), ('3 - 4', '3 - 4'), ('4 - 5', '4 - 5'), ('5 - 6', '5 - 6'), ('6 - 7', '6 - 7'), ('7 - 8', '7 - 8'), ('8 - 9', '8 - 9'), ('9 - 10', '9 - 10')], max_length=10),
        ),
    ]
