# Generated by Django 3.0.3 on 2020-04-04 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0023_auto_20200404_1528'),
    ]

    operations = [
        migrations.CreateModel(
            name='CVFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='jobs')),
            ],
        ),
        migrations.RemoveField(
            model_name='jobprofile',
            name='curriculum_vitae',
        ),
        migrations.AddField(
            model_name='jobprofile',
            name='curriculum_vitae',
            field=models.ManyToManyField(blank=True, to='posts.CVFile'),
        ),
    ]
