# Generated by Django 3.0.3 on 2020-04-04 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0024_auto_20200404_1531'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobprofile',
            old_name='curriculum_vitae',
            new_name='curriculum_vitaes',
        ),
    ]
