# Generated by Django 3.0.3 on 2020-04-04 16:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0026_auto_20200404_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='phone_number',
            field=models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
