# Generated by Django 3.0.3 on 2020-04-06 18:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0028_aboutus_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutus',
            options={'ordering': ('order',), 'verbose_name': 'About Us', 'verbose_name_plural': 'About Us'},
        ),
        migrations.AlterField(
            model_name='post',
            name='highlight',
            field=models.TextField(help_text='Maximum characters allowed are 170', max_length=210, validators=[django.core.validators.MinLengthValidator(170)]),
        ),
    ]
