# Generated by Django 3.0.3 on 2020-04-07 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0029_auto_20200406_1823'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnologyPartner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='partners')),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='highlight',
            field=models.TextField(help_text='Maximum characters allowed are 200', max_length=200),
        ),
    ]
