# Generated by Django 3.0.3 on 2020-06-02 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0030_auto_20200407_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='technologypartner',
            name='link',
            field=models.URLField(default='https://www.google.com', max_length=255),
            preserve_default=False,
        ),
    ]
