# Generated by Django 3.0.3 on 2020-11-07 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0031_technologypartner_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='EngineeringProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('discription', models.CharField(max_length=255)),
            ],
        ),
    ]
