# Generated by Django 3.0.3 on 2020-11-07 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0032_engineeringproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engineeringproduct',
            name='discription',
            field=models.TextField(max_length=255),
        ),
    ]
