# Generated by Django 3.0.3 on 2020-11-07 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0033_auto_20201107_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engineeringproduct',
            name='discription',
            field=models.TextField(),
        ),
    ]
